import time
from webbrowser import Chrome
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
import kullanıcı as kb
import random


class Browser:
    def __init__(self,link):
        self.link = link
        Browser.GetVpn(self)


    def GetVpn(self): #İnstagramı açar.

        print("VPN sayfası birazdan açılacaktır. VPN'yi el ile çalıştırmayı unutmayın.")
        time.sleep(2)
        self.browser = webdriver.Chrome("/Users/yarentasdemir/Desktop/chromedriver")
        self.browser.get(self.link)
        WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
        time.sleep(3)
        self.browser.find_element_by_xpath("/html/body/div[5]/div[2]/div/div/div[2]/div[2]/div/div").click()
        print("Açılan ekranda uzantı ekleye tıklayın. Yaklaşık 5 saniye gelecek google sayfasını kapatın. Uzantılarda Zenmate VPN'yi başa tutturun. Zenmate VPN'yi açın ve reklamları geçin. Bir IP adresine bağlanın. IP adresine bağlanmada hata alırsanız lokasyon değiştirip tekrar bağlanın.")
        time.sleep(30)    
        Browser.Takipcigir(self)


    def Takipcigir(self):
        try:
            self.browser.get("https://takipcigir.com/login")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            print("Siteye giriş yapılmıştır")
            nick = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[2]/form/div[1]/input")
            pw = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[2]/form/div[2]/input")
            nick.send_keys(kb.nickname)
            pw.send_keys(kb.sifre)
            self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[2]/form/span/button").click()
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(10)
            print("Hesaba başarılı şekilde girilmiştir.")
            self.browser.find_element_by_xpath("/html/body/div[2]/div/ul/li[5]/a").click()
            print("Video izletme sayfası açılmıştır.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            follow = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div/input")
            follow.send_keys(kb.link)
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            print("Video izleme atılacak video/fotoğraf seçilmiştir.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            adet = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div[2]/input")
            adet.send_keys(kb.sayi)
            print("{} adet video izletme işlemi başlamıştır.".format(kb.sayi))
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            time.sleep(2)
            Browser.takipstar(self)
        except:
            print("Takipcigir sitesinde hata bulunmuştur.")
            Browser.takipstar(self)


    def takipstar(self):
        try:
            self.browser.get("https://takipstar.com/giris")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            print("Siteye giriş yapılmıştır")
            nick = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/div[1]/input")
            pw = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/div[2]/input")
            nick.send_keys(kb.nickname)
            pw.send_keys(kb.sifre)
            self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/span[2]/button").click()
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(10)
            print("Hesaba başarılı şekilde girilmiştir.")
            self.browser.find_element_by_xpath("/html/body/div[1]/div/ul/li[5]/a").click()
            print("Video izletme sayfası açılmıştır.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            follow = self.browser.find_element_by_xpath("/html/body/div[2]/div[2]/div[1]/div[2]/div[2]/form/div/input")
            follow.send_keys(kb.link)
            self.browser.find_element_by_xpath("/html/body/div[2]/div[2]/div[1]/div[2]/div[2]/form/button").click()
            print("Video izleme atılacak video/fotoğraf seçilmiştir.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            adet = self.browser.find_element_by_xpath("/html/body/div[2]/div[2]/div[1]/div[2]/div[2]/form/div[2]/input")
            adet.send_keys(kb.sayi)
            print("{} adet video izletme işlemi başlamıştır.".format(kb.sayi))
            self.browser.find_element_by_xpath("/html/body/div[2]/div[2]/div[1]/div[2]/div[2]/form/button").click()
            time.sleep(2)
            Browser.takipcimx(self)
        except:
            print("Takipstar sitesinde hata bulunmuştur.")
            Browser.takipcimx(self)


    def takipcimx(self):
        try:
            self.browser.get("https://takipcimx.com/member")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            print("Siteye giriş yapılmıştır")
            nick = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[3]/form/div[1]/input")
            pw = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[3]/form/div[2]/input")
            nick.send_keys(kb.nickname)
            pw.send_keys(kb.sifre)
            self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[3]/form/span/button").click()
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(10)
            print("Hesaba başarılı şekilde girilmiştir.")
            self.browser.find_element_by_xpath("/html/body/div[2]/div/ul/li[5]/a").click()
            print("Video izletme sayfası açılmıştır.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            follow = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div/input")
            follow.send_keys(kb.link)
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            print("Video izleme atılacak video/fotoğraf seçilmiştir.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            adet = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div[2]/input")
            adet.send_keys(kb.sayi)
            print("{} adet video izletme işlemi başlamıştır.".format(kb.sayi))
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            time.sleep(2)
            Browser.instahilecin(self)
        except:
            print("Takipcimx sitesinde hata bulunmuştur.")
            Browser.instahilecin(self)
 

    def instahilecin(self):
        try:
            self.browser.get("https://instahilecin.net/login")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            print("Siteye giriş yapılmıştır")
            nick = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[2]/form/div[1]/input")
            pw = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[2]/form/div[2]/input")
            nick.send_keys(kb.nickname)
            pw.send_keys(kb.sifre)
            self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[2]/form/span/button").click()
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(10)
            print("Hesaba başarılı şekilde girilmiştir.")
            self.browser.find_element_by_xpath("/html/body/div[2]/div/ul/li[5]/a").click()
            print("Video izletme sayfası açılmıştır.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            follow = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div/input")
            follow.send_keys(kb.link)
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            print("Video izleme atılacak video/fotoğraf seçilmiştir.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            adet = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div[2]/input")
            adet.send_keys(kb.sayi)
            print("{} adet video izletme işlemi başlamıştır.".format(kb.sayi))
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            time.sleep(2)            
            Browser.takipcikutusu(self)
        except:
            print("İnstahilecin sitesinde hata bulunmuştur.")
            Browser.takipcikutusu(self)

 
    def takipcikutusu(self):
        try:
            self.browser.get("https://takipcikutusu.com/member")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            print("Siteye giriş yapılmıştır")
            nick = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/div[1]/input")
            pw = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/div[2]/input")
            nick.send_keys(kb.nickname)
            pw.send_keys(kb.sifre)
            self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/span/button").click()
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(10)
            print("Hesaba başarılı şekilde girilmiştir.")
            self.browser.find_element_by_xpath("/html/body/div[1]/div/ul/li[5]/a").click()
            print("Video izletme sayfası açılmıştır.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            follow = self.browser.find_element_by_xpath("/html/body/div[2]/div[2]/div[1]/div[2]/div[2]/form/div/input")
            follow.send_keys(kb.link)
            self.browser.find_element_by_xpath("/html/body/div[2]/div[2]/div[1]/div[2]/div[2]/form/button").click()
            print("Video izleme atılacak video/fotoğraf seçilmiştir.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            adet = self.browser.find_element_by_xpath("/html/body/div[2]/div[2]/div[1]/div[2]/div[2]/form/div[2]/input")
            adet.send_keys(kb.sayi)
            print("{} adet video izletme işlemi başlamıştır.".format(kb.sayi))
            self.browser.find_element_by_xpath("/html/body/div[2]/div[2]/div[1]/div[2]/div[2]/form/button").click()
            time.sleep(2)
            Browser.medyahizmeti(self)
        except:
            print("Takipcikutusu sitesinde hata bulunmuştur.")
            Browser.medyahizmeti(self)


    def medyahizmeti(self):
        try:
            self.browser.get("https://medyahizmeti.com/member")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            print("Siteye giriş yapılmıştır")
            nick = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[3]/form/div[1]/input")
            pw = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[3]/form/div[2]/input")
            nick.send_keys(kb.nickname)
            pw.send_keys(kb.sifre)
            self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[3]/form/span/button").click()
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(10)
            print("Hesaba başarılı şekilde girilmiştir.")
            self.browser.find_element_by_xpath("/html/body/div[2]/div/ul/li[5]/a").click()
            print("Video izletme sayfası açılmıştır.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            follow = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div/input")
            follow.send_keys(kb.link)
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            print("Video izleme atılacak video/fotoğraf seçilmiştir.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            adet = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div[2]/input")
            adet.send_keys(kb.sayi)
            print("{} adet video izletme işlemi başlamıştır.".format(kb.sayi))
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            time.sleep(2)
            Browser.bayitakipci(self)
        except:
            print("Medyahizmeti sitesinde hata bulunmuştur.")
            Browser.bayitakipci(self)

 
    def bayitakipci(self):
        try:
            self.browser.get("https://bayitakipci.com/memberlogin")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            print("Siteye giriş yapılmıştır")
            nick = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[3]/form/div[1]/input")
            pw = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[3]/form/div[2]/input")
            nick.send_keys(kb.nickname)
            pw.send_keys(kb.sifre)
            self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[3]/form/span/button").click()
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(10)
            print("Hesaba başarılı şekilde girilmiştir.")
            self.browser.find_element_by_xpath("/html/body/div[2]/div/ul/li[5]/a").click()
            print("Video izletme sayfası açılmıştır.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            follow = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div/input")
            follow.send_keys(kb.link)
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            print("Video izleme atılacak video/fotoğraf seçilmiştir.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            adet = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div[2]/input")
            adet.send_keys(kb.sayi)
            print("{} adet video izletme işlemi başlamıştır.".format(kb.sayi))
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            time.sleep(2)
            Browser.ototakipci(self)
        except:
            print("Bayitakipci sitesinde hata bulunmuştur.")
            Browser.ototakipci(self)


    def ototakipci(self):
        try:
            self.browser.get("https://ototakipci.com/giris")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            print("Siteye giriş yapılmıştır")
            nick = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/div[1]/input")
            pw = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/div[2]/input")
            nick.send_keys(kb.nickname)
            pw.send_keys(kb.sifre)
            self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/span[2]/button").click()
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(10)
            print("Hesaba başarılı şekilde girilmiştir.")
            self.browser.find_element_by_xpath("/html/body/div[2]/div/ul/li[5]/a").click()
            print("Video izletme sayfası açılmıştır.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            follow = self.browser.find_element_by_xpath("/html/body/div[3]/div[2]/div[1]/div/div[2]/form/div/input")
            follow.send_keys(kb.link)
            self.browser.find_element_by_xpath("/html/body/div[3]/div[2]/div[1]/div/div[2]/form/button").click()
            print("Video izleme atılacak video/fotoğraf seçilmiştir.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            adet = self.browser.find_element_by_xpath("/html/body/div[3]/div[2]/div[1]/div/div[2]/form/div[2]/input")
            adet.send_keys(kb.sayi)
            print("{} adet video izletme işlemi başlamıştır.".format(kb.sayi))
            self.browser.find_element_by_xpath("/html/body/div[3]/div[2]/div[1]/div/div[2]/form/button").click()
            time.sleep(2)
            Browser.anindabegeni(self)
        except:
            print("Ototakipci sitesinde hata bulunmuştur.")
            Browser.anindabegeni(self)


    def anindabegeni(self):
        try:
            self.browser.get("https://i.anindabegeni.com/member")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            print("Siteye giriş yapılmıştır")
            nick = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/div[1]/input")
            pw = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/div[2]/input")
            nick.send_keys(kb.nickname)
            pw.send_keys(kb.sifre)
            self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/span[2]/button").click()
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(10)
            print("Hesaba başarılı şekilde girilmiştir.")
            self.browser.find_element_by_xpath("/html/body/div[2]/div/ul/li[5]/a").click()
            print("Video izletme sayfası açılmıştır.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            follow = self.browser.find_element_by_xpath("/html/body/div[3]/div[2]/div[1]/div[2]/div[2]/form/div/input")
            follow.send_keys(kb.link)
            self.browser.find_element_by_xpath("/html/body/div[3]/div[2]/div[1]/div[2]/div[2]/form/button").click()
            print("Video izleme atılacak video/fotoğraf seçilmiştir.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            adet = self.browser.find_element_by_xpath("/html/body/div[3]/div[2]/div[1]/div[2]/div[2]/form/div[2]/input")
            adet.send_keys(kb.sayi)
            print("{} adet video izletme işlemi başlamıştır.".format(kb.sayi))
            self.browser.find_element_by_xpath("/html/body/div[3]/div[2]/div[1]/div[2]/div[2]/form/button").click()
            time.sleep(2)
            Browser.canlitakipci(self)
        except:
            print("Anindabegeni sitesinde hata bulunmuştur.")
            Browser.canlitakipci(self)

 
    def canlitakipci(self):
        try:
            self.browser.get("https://canlitakipci.com/login")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            print("Siteye giriş yapılmıştır")
            nick = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/div[1]/input")
            pw = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/div[2]/input")
            nick.send_keys(kb.nickname)
            pw.send_keys(kb.sifre)
            self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/span[2]/button").click()
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(10)
            print("Hesaba başarılı şekilde girilmiştir.")
            self.browser.find_element_by_xpath("/html/body/div[1]/div/ul/li[5]/a").click()
            print("Video izletme sayfası açılmıştır.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            follow = self.browser.find_element_by_xpath("/html/body/div[3]/div[2]/div[1]/div/div[2]/form/div/input")
            follow.send_keys(kb.link)
            self.browser.find_element_by_xpath("/html/body/div[3]/div[2]/div[1]/div/div[2]/form/button").click()
            print("Video izleme atılacak video/fotoğraf seçilmiştir.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            adet = self.browser.find_element_by_xpath("/html/body/div[3]/div[2]/div[1]/div/div[2]/form/div[2]/input")
            adet.send_keys(kb.sayi)
            print("{} adet video izletme işlemi başlamıştır.".format(kb.sayi))
            self.browser.find_element_by_xpath("/html/body/div[3]/div[2]/div[1]/div/div[2]/form/button").click()
            time.sleep(2)
            Browser.instavevo(self)
        except:
            print("Canlitakipci sitesinde hata bulunmuştur.")
            Browser.instavevo(self)

 
    def instavevo(self): 
        try:
            self.browser.get("https://instavevo.com/member")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            print("Siteye giriş yapılmıştır")
            nick = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/div[1]/input")
            pw = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/div[2]/input")
            nick.send_keys(kb.nickname)
            pw.send_keys(kb.sifre)
            self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div/form/span[2]/button").click()
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(10)
            print("Hesaba başarılı şekilde girilmiştir.")
            self.browser.find_element_by_xpath("/html/body/div[1]/div/ul/li[5]/a").click()
            print("Video izletme sayfası açılmıştır.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            follow = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div/input")
            follow.send_keys(kb.link)
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            print("Video izleme atılacak video/fotoğraf seçilmiştir.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            adet = self.browser.find_element_by_xpath("/html/body/div[2]/div[2]/div[1]/div[2]/div[2]/form/div[2]/input")
            adet.send_keys(kb.sayi)
            print("{} adet video izletme işlemi başlamıştır.".format(kb.sayi))
            self.browser.find_element_by_xpath("/html/body/div[2]/div[2]/div[1]/div[2]/div[2]/form/button").click()
            time.sleep(2)
            Browser.takipcikrali(self)
        except:
            print("İnstavevo sitesinde hata bulunmuştur.")
            Browser.takipcikrali(self)


    def takipcikrali(self): 
        try:
            self.browser.get("https://takipcikrali.com/login")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            print("Siteye giriş yapılmıştır")
            nick = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[2]/form/div[1]/input")
            pw = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[2]/form/div[2]/input")
            nick.send_keys(kb.nickname)
            pw.send_keys(kb.sifre)
            self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[2]/form/span/button").click()
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(10)
            print("Hesaba başarılı şekilde girilmiştir.")
            self.browser.find_element_by_xpath("/html/body/div[2]/div/ul/li[2]/a").click()
            print("Video izletme sayfası açılmıştır.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            follow = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div/input")
            follow.send_keys(kb.link)
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            print("Video izleme atılacak video/fotoğraf seçilmiştir.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            adet = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div[2]/input")
            adet.send_keys(kb.sayi)
            print("{} adet video izletme işlemi başlamıştır.".format(kb.sayi))
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            time.sleep(2)
            Browser.anatakipci(self)
        except:
            print("Takipcikrali sitesinde hata bulunmuştur.")
            Browser.anatakipci(self)


    def anatakipci(self):
        try:
            self.browser.get("https://anatakip.com/login")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            print("Siteye giriş yapılmıştır")
            nick = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[2]/form/div[1]/input")
            pw = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[2]/form/div[2]/input")
            nick.send_keys(kb.nickname)
            pw.send_keys(kb.sifre)
            self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[2]/form/span/button").click()
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(10)
            print("Hesaba başarılı şekilde girilmiştir.")
            self.browser.find_element_by_xpath("/html/body/div[2]/div/ul/li[5]/a").click()
            print("Video izletme sayfası açılmıştır.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            follow = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div/input")
            follow.send_keys(kb.link)
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            print("Video izleme atılacak video/fotoğraf seçilmiştir.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            adet = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div[2]/input")
            adet.send_keys(kb.sayi)
            print("{} adet video izletme işlemi başlamıştır.".format(kb.sayi))
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            time.sleep(2)
            Browser.bigtakip(self)
        except:
            print("Anatakipci sitesinde hata bulunmuştur.")
            Browser.bigtakip(self)


    def bigtakip(self):
        try:
            self.browser.get("https://bigtakip.com/member")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            print("Siteye giriş yapılmıştır")
            nick = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[3]/form/div[1]/input")
            pw = self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[3]/form/div[2]/input")
            nick.send_keys(kb.nickname)
            pw.send_keys(kb.sifre)
            self.browser.find_element_by_xpath("/html/body/span/section/main/article/div/div/div[3]/form/span/button").click()
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(10)
            print("Hesaba başarılı şekilde girilmiştir.")
            self.browser.find_element_by_xpath("/html/body/div[2]/div/ul/li[2]/a").click()
            print("Video izletme sayfası açılmıştır.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            follow = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div/input")
            follow.send_keys(kb.link)
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            print("Video izleme atılacak video/fotoğraf seçilmiştir.")
            WebDriverWait(Chrome, 0, poll_frequency=0.5, ignored_exceptions=None)
            time.sleep(3)
            adet = self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/div[2]/input")
            adet.send_keys(kb.sayi)
            print("{} adet video izletme işlemi başlamıştır.".format(kb.sayi))
            self.browser.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/div/div[2]/form/button").click()
            time.sleep(2)
            print("Takip işlemi bitmiştir")
        except:
            print("Bigtakip sitesinde hata bulunmuştur.")
            print("Takip işlemi bitmiştir")
 
